config/routes.rb
Inventario::Application.routes.draw do
  resources :itens

  root 'itens#index'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/itens_controller.rb
class ItensController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /itens
  # GET /itens.json
  def index
    @itens = Item.all
  end

  # GET /itens/1
  # GET /itens/1.json
  def show
  end

  # GET /itens/new
  def new
    @item = Item.new
  end

  # GET /itens/1/edit
  def edit
  end

  # POST /itens
  # POST /itens.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itens/1
  # PATCH/PUT /itens/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itens/1
  # DELETE /itens/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to itens_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:classe, :tombamento, :descricao, :localizacao, :valor_aquisicao, :dt_aquisicao, :ec, :pub, :evf, :fr, :valor_mercado, :vbr, :vr, :nv)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/itens_helper.rb
module ItensHelper
end

app/views/itens/_form.html.haml
= simple_form_for(@item) do |f|
  = f.error_notification

  .form-inputs
    = f.input :classe
    = f.input :tombamento
    = f.input :descricao
    = f.input :localizacao
    = f.input :valor_aquisicao
    = f.input :dt_aquisicao, as: :date, order: [:day, :month, :year]
    = f.input :ec
    = f.input :pub
    = f.input :evf
    = f.input :fr
    = f.input :valor_mercado
    = f.input :vbr
    = f.input :vr
    = f.input :nv

  .form-actions
    = f.button :submit, value: 'Salvar'

app/views/itens/edit.html.haml
%h4 Editar item

= link_to 'Voltar', itens_path
= render 'form'
= link_to 'Ver', @item

= link_to 'Voltar', itens_path

app/views/itens/index.html.haml
%h4 Bens não localizados fisicamente
- i = 0
= link_to 'Novo Item', new_item_path
%table.table.table-condensed.table-striped#table-filtros.table-bordered.table-hover
  %thead
    %tr
      %th Nº
      %th Classe
      %th Tombamento
      %th Descricao
      %th{"filter-type" => "ddl"} Orgão
      %th{"filter-type" => "ddl"} Localizacao
      %th{class: 'tr_p'} Valor Aq.
      %th Data Aq.
      %th{"filter" => "false"} EC
      %th{"filter" => "false"} PUB
      %th{"filter" => "false"} EVF
      %th{"filter" => "false"} FR
      %th Valor M.
      %th{"filter" => "false"} VBR
      %th{"filter" => "false"} VR
      %th{"filter" => "false"} NV
      %th{"filter" => "false"}
      %th{"filter" => "false"}
      %th{"filter" => "false"}
  %tbody
    - @itens.each do |item|
      %tr
        %td= i += 1
        %td= item.classe
        %td= item.tombamento
        %td= item.descricao
        %td SEPOG
        %td= item.localizacao
        %td{class: "table-filtros_filter_6"}= item.valor_aquisicao
        %td= item.dt_aquisicao.strftime('%d/%m/%y')
        %td= item.ec
        %td= item.pub
        %td= item.evf
        %td= item.fr
        %td= item.valor_mercado
        %td= item.vbr
        %td= item.vr
        %td= item.nv
        %td
          = link_to item do
            %i.icon-search
        %td
          = link_to edit_item_path(item) do
            %i.icon-edit
        %td
          = link_to item, :method => :delete, :data => { :confirm => 'Are you sure?' } do
            %i.icon-trash

%br

= link_to 'Novo Item', new_item_path

app/views/itens/new.html.haml
%h4 Novo item

= link_to 'Voltar', itens_path
= render 'form'
= link_to 'Voltar', itens_path

app/views/itens/show.html.haml
%p#notice= notice

%p
  %b Classe:
  = @item.classe
%p
  %b Tombamento:
  = @item.tombamento
%p
  %b Descricao:
  = @item.descricao
%p
  %b Localizacao:
  = @item.localizacao
%p
  %b Valor aquisicao:
  = @item.valor_aquisicao
%p
  %b Dt aquisicao:
  = @item.dt_aquisicao
%p
  %b Ec:
  = @item.ec
%p
  %b Pub:
  = @item.pub
%p
  %b Evf:
  = @item.evf
%p
  %b Fr:
  = @item.fr
%p
  %b Valor mercado:
  = @item.valor_mercado
%p
  %b Vbr:
  = @item.vbr
%p
  %b Vr:
  = @item.vr
%p
  %b Nv:
  = @item.nv

= link_to 'Editar', edit_item_path(@item)
\|
= link_to 'Voltar', itens_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head>
    %title Inventario
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    .navbar
      .navbar-inner.navbar-topo
        .container.container-topo
          .titulo
            = image_tag "logo-fortaleza.png"
            .texto_projeto
              %h4.nome_projeto Gestão de Bens
              %span.pmf Prefeitura de Fortaleza    

    .container-fluid
      .div.row-fluid
        = yield